# CMake generated Testfile for 
# Source directory: D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0
# Build directory: D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(SimpleTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/Debug/simple_test.exe")
  set_tests_properties(SimpleTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;113;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(SimpleTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/Release/simple_test.exe")
  set_tests_properties(SimpleTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;113;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(SimpleTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/MinSizeRel/simple_test.exe")
  set_tests_properties(SimpleTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;113;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(SimpleTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/RelWithDebInfo/simple_test.exe")
  set_tests_properties(SimpleTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;113;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
else()
  add_test(SimpleTest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(IntegrationTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/Debug/integration_test.exe")
  set_tests_properties(IntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;114;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(IntegrationTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/Release/integration_test.exe")
  set_tests_properties(IntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;114;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(IntegrationTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/MinSizeRel/integration_test.exe")
  set_tests_properties(IntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;114;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(IntegrationTest "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/bin/RelWithDebInfo/integration_test.exe")
  set_tests_properties(IntegrationTest PROPERTIES  _BACKTRACE_TRIPLES "D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;114;add_test;D:/思朗-相关资料/cantera重构-5.27/yaml-convector-2.0/yaml-convector-2.0/CMakeLists.txt;0;")
else()
  add_test(IntegrationTest NOT_AVAILABLE)
endif()
